// Code generated by goyacc eqn.y. DO NOT EDIT.

//line eqn.y:2
package eqnml

import __yyfmt__ "fmt"

//line eqn.y:2

import "html"

//line eqn.y:17
type yySymType struct {
	yys  int
	s    string
	b    []byte
	bs   [][]byte
	bss  [][][]byte
	line line
}

const MATRIX = 57346
const ABOVE = 57347
const MROW = 57348
const VMATRIX = 57349
const BACKSLASH2 = 57350
const EOF = 57351
const NOTEQN = 57352
const EQNSTART = 57353
const EQNEND = 57354
const QTEXT = 57355
const CONTIG = 57356
const SUP = 57357
const SUB = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"MATRIX",
	"ABOVE",
	"MROW",
	"VMATRIX",
	"BACKSLASH2",
	"EOF",
	"NOTEQN",
	"EQNSTART",
	"EQNEND",
	"QTEXT",
	"CONTIG",
	"SUP",
	"SUB",
	"'{'",
	"'}'",
	"'~'",
	"'^'",
	"'&'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line eqn.y:73

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 79

var yyAct = [...]int8{
	3, 26, 23, 12, 14, 13, 18, 16, 1, 30,
	25, 10, 17, 9, 19, 20, 12, 0, 0, 28,
	5, 6, 29, 12, 4, 24, 7, 8, 12, 0,
	0, 31, 32, 10, 0, 9, 27, 2, 0, 0,
	0, 15, 5, 6, 0, 0, 4, 21, 7, 8,
	10, 0, 9, 22, 0, 11, 0, 0, 0, 5,
	6, 0, 10, 4, 9, 7, 8, 0, 0, 0,
	0, 5, 6, 0, 0, 4, 0, 7, 8,
}

var yyPact = [...]int16{
	58, -1000, 46, -11, 58, -1000, -1000, -1000, -1000, -10,
	-7, -1000, -11, 58, 58, 29, 58, -15, -1000, -11,
	-11, -1000, 7, 58, -1000, 1, -1000, 58, -1000, 58,
	58, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 36, 0, 1, 12, 10, 8,
}

var yyR1 = [...]int8{
	0, 6, 1, 1, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 3, 3, 5, 5, 5, 4, 4,
}

var yyR2 = [...]int8{
	0, 2, 1, 2, 3, 1, 1, 1, 1, 4,
	3, 3, 5, 0, 1, 1, 3, 3, 0, 1,
}

var yyChk = [...]int16{
	-1000, -6, -1, -2, 17, 13, 14, 19, 20, 6,
	4, 9, -2, 16, 15, -1, 17, -4, 13, -2,
	-2, 18, -1, 17, 18, -5, -3, -1, 18, 21,
	8, -3, -3,
}

var yyDef = [...]int8{
	0, -2, 0, 2, 0, 5, 6, 7, 8, 0,
	18, 1, 3, 0, 0, 0, 0, 0, 19, 10,
	11, 4, 0, 13, 9, 0, 15, 14, 12, 13,
	13, 16, 17,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 21, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 20, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 17, 3, 18, 19,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line eqn.y:29
		{
			yylex.(*lexer).math = yyDollar[1].b
			return 1
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:33
		{
			yyVAL.b = yyDollar[1].b
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line eqn.y:35
		{
			yyVAL.b = append(yyDollar[1].b, yyDollar[2].b...)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line eqn.y:39
		{
			yyVAL.b = yyDollar[2].b
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:41
		{
			yyVAL.b = []byte("<mtext>" + html.EscapeString(yyDollar[1].s) + "</mtext>")
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:43
		{
			yyVAL.b = yyDollar[1].b
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:45
		{
			yyVAL.b = []byte("<mspace class='s1'/>")
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:47
		{
			yyVAL.b = []byte("<mspace class='s0'/>")
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line eqn.y:49
		{
			yyVAL.b = append(append([]byte("<mrow>"), yyDollar[3].b...), "</mrow>"...)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line eqn.y:51
		{
			yyVAL.b = append(append(append(append([]byte("<msub><mrow>"), yyDollar[1].b...), "</mrow><mrow>"...), yyDollar[3].b...), "</msub>"...)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line eqn.y:53
		{
			yyVAL.b = append(append(append(append([]byte("<msup><mrow>"), yyDollar[1].b...), "</mrow><mrow>"...), yyDollar[3].b...), "</msup>"...)
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line eqn.y:55
		{
			yyVAL.b = vmatrix(yyDollar[2].s, yyDollar[4].bss)
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line eqn.y:58
		{
			yyVAL.b = nil
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line eqn.y:63
		{
			yyVAL.bss = [][][]byte{[][]byte{yyDollar[1].b}}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line eqn.y:65
		{
			yyVAL.bss = yyDollar[1].bss
			yyVAL.bss[len(yyVAL.bss)-1] = append(yyVAL.bss[len(yyVAL.bss)-1], yyDollar[3].b)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line eqn.y:67
		{
			yyVAL.bss = yyDollar[1].bss
			yyVAL.bss = append(yyVAL.bss, [][]byte{yyDollar[3].b})
		}
	case 18:
		yyDollar = yyS[yypt-0 : yypt+1]
//line eqn.y:70
		{
			yyVAL.s = ""
		}
	}
	goto yystack /* stack new state and value */
}
